name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v2
      with:
        # TODO: angular 9 build does not run on node > 14
        node-version: 14
        cache: npm
        cache-dependency-path: package-lock.json

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npm run build
     
    - name: Lint
      run: npm run lint